version: '3.8'

services:
  bot-api:
    build: .
    container_name: marketing_bot
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
      - sql_db # Depende de ambas
    environment:
      - MONGO_URI=mongodb://admin:root-1756-sffrgd-ddj86t@mongo_db:27017/marketing_db?authSource=admin
      - SQL_URL=postgresql://user_admin:pass_123@sql_db:5432/productos_db

  mongo_db:
    image: mongo:latest
    container_name: marketing-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root-1756-sffrgd-ddj86t
    volumes:
      - mongo_data:/data/db

  # Nueva Base de Datos SQL
  sql_db:
    image: postgres:latest
    container_name: productos-sql
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: pass_123
      POSTGRES_DB: productos_db
    ports:
      - "5433:5432" # Mapeo externo 5433 para no chocar si tienes otro local
    volumes:
      - sql_data:/var/lib/postgresql/data 
      - ./YOUP/SQL_scripts:/docker-entrypoint-initdb.d/

volumes:
  mongo_data:
  sql_data: # Nuevo volumen para SQL